export const ADD_TO_DEFECT_REQUEST = 'ADD_TO_DEFECT_REQUEST';
export const ADD_TO_DEFECT_SUCCESS = 'ADD_TO_DEFECT_SUCCESS';
export const ADD_TO_DEFECT_FAIL = 'ADD_TO_DEFECT_FAIL';
export const CLOSE_DEFECT_REQUEST = 'CLOSE_DEFECT_REQUEST';
export const CLOSE_DEFECT_RESET = 'CLOSE_DEFECT_RESET';
